env: ${args.env|envs.ENV}
name: 'cetus'

infra:
  bucket_name: ${args.bucket_name|envs.BUCKET_NAME}
  stack_name: ${args.stack_name|envs.STACK_NAME}
  function_name: ${args.function_name|envs.FUNCTION_NAME}

spark:
  properties:
    'spark.sql.session.timeZone': 'UTC'

logging:
  level: ${envs.LOG_LEVEL?INFO}
  format: '%(asctime)s.%(msecs)03d %(levelname)-8s %(module)s.%(funcName)s(%(lineno)d) %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'

source_path: 's3://vitalibo-sandbox-us-east-1/cetus/sample-${args.frac?0.1}.csv'

source:
  format: 'csv'
  path: '${envs.LOCAL_PATH|source_path}'
  header: true
  inferSchema: true

transform:
  version: 'v1'
  scale: 2
  dimensions:
    path:
      - 'Month'
      - 'Region'
    file:
      - 'Category'
      - 'Customer Segment'
      - 'Sales Channel'
    body:
      - 'Product'
  metrics:
    - 'Sales'
    - 'Profit'
    - 'Quantity'
