env: ${args.env|envs.ENV}
name: 'cetus'

s3_bucket: ${args.s3_bucket|envs.S3_BUCKET}
stack_name: ${args.stack_name|envs.STACK_NAME}
function_name: ${args.function_name|envs.FUNCTION_NAME}

logging:
  level: ${envs.LOG_LEVEL?INFO}
  format: '%(asctime)s.%(msecs)03d %(levelname)-8s %(module)s.%(funcName)s(%(lineno)d) %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'

distributor:
  cron: '0 0 * * ? *'

file_assets_bucket_name: 'vitalibo-sandbox-us-east-1'

spark:
  properties:
    'spark.sql.session.timeZone': 'UTC'
